print("Library Management System Initialized!")
print("Student/Faculty Registration Modules Added")
print("New Registration Modules Enabled")
print("Implementation of Login Features")
print("Changes done from Conflict Branch")